### ISSUE TITLE
Erdpy 0.2.8 does not accept old format addresses at --receiver

### ISSUE THREAD

**Issue by cochinescu** [ElrondNetwork/erdpy#9]
> Error message:
> CRITICAL:cli:Proxy request error for url [https://wallet-api.elrond.com/transaction/send]: {'error': 'invalid hex receiver address provided : failed converting data to bytes: invalid character not part of charset: 98'}

After replacing the old format address at --receiver with a new format address starting with erd1 it worked just fine.

**Comment by andreibancioiu** [comment]
This is correct. Now we recommend bech32 addresses to be used. Though, the latest `erdpy` update includes an automatic converter which recognizes the provided format of the address, applies conversions if necessary and uses only bech32 format when communicating with the blockchain.

**Comment by cochinescu** [comment]
Great, thank you!
